# Generated by Django 3.1.6 on 2022-01-04 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonctionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name=' Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prenom')),
                ('genre', models.CharField(max_length=30, verbose_name='Genre')),
                ('telephone', models.CharField(max_length=30, verbose_name='Telephone')),
                ('poste', models.CharField(max_length=20, verbose_name='Poste')),
            ],
        ),
        migrations.CreateModel(
            name='Mere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prenom')),
                ('genre', models.CharField(max_length=30, verbose_name='Genre')),
                ('date_naissance_mere', models.DateField(verbose_name='Date de naissance pere')),
                ('lieu_naissance_mere', models.CharField(max_length=30, verbose_name='Lieu de Naissance pere')),
                ('fonction_mere', models.CharField(max_length=30, verbose_name='Fonction Pere')),
            ],
        ),
        migrations.CreateModel(
            name='Pere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prenom')),
                ('genre', models.CharField(max_length=30, verbose_name='Genre')),
                ('date_naissance_pere', models.DateField(verbose_name='Date de naissance pere')),
                ('lieu_naissance_pere', models.CharField(max_length=30, verbose_name='Lieu de Naissance pere')),
                ('fonction_pere', models.CharField(max_length=30, verbose_name='Fonction Pere')),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrondissement', models.CharField(max_length=50, verbose_name='Arrondissement')),
                ('nom', models.CharField(max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Prenom')),
                ('genre', models.CharField(max_length=30, verbose_name='Genre')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=30, verbose_name='Lieu de Naissance')),
                ('groupe_sanguin', models.CharField(max_length=10, verbose_name='Groupe sanguin')),
                ('fonctionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naissanceAPP.fonctionnaire')),
                ('mere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naissanceAPP.mere')),
                ('pere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naissanceAPP.pere')),
            ],
        ),
    ]
